document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('searchInput');
    const estafadoresList = document.getElementById('estafadoresList');
    const ul = document.getElementById('estafadoresUl'); // Obtener la lista ul

    const estafadores = [
        'BOOSTED DOTA 2', ' BOOSTING SIR', 'BEARS STORE', 'CRASH DOTA 2 STORE', 'Coorp Perez', 'DOTA 2 INTERNACIONAL', 'DOTA SCRIPT', 'Dota Store', 'Dota Deer Store', 'DK STORE',
        'Dota Eagle Store', 'Dota Bulldog Store', 'EL TIO INVOKER', 'EL PUDGESOR', 'EL TIO JUGGERNAUT', 'FENIX STORE', 'FIREBIRD DOTA2', 'FOXES STORE', 'GAMER PERU', 'GAMERS CLUB',
        'JR.DOTA STORE', 'JUEGOS CENTER', 'MUNDO VIRTUAL', 'PUCK STORE', 'PEREZ CORP', 'PHOENIX STORE( DOTA Eagle store)', 'PANDITA STORE (DOTA INTERNACIONAL)', 'RASH CORP', 'SMITH STORE'
        , 'STORE GAMING', 'STORE EXCLUSIVO', 'TOUCH ARCADE', 'UNOWN STORE', 'WARNERBOOSTING', 'WOLF STORE', 'ANDY FRETEL', 'ANDY FH', 'ANDY FH', 'ANDY LLV DE LOS KINGS', 'ABRAHAM NANO', 'ARON ORTEGA LLANQUE', 'AARON DANIEL MANSILLA CONTRERAS'
        , 'AARON RIOS', 'ANTHONY SALVADOR HUAMANI FIERRO', ' ALBERT BENJAMIN QUISPE QUISPE', 'ALEX TICONA MAMANI', 'ADOLFO GUILLERMO CIEZA', 'ANGEL GABRIEL CONDORI SULLCACCORI', 'AFNET OLIVER PINEDA PUJAY', 'ANGEL MANUEL SAAV', 'ANGEL MANUEL SAAVEDRA RODRIGUEZ'
        , 'ANTONIO CONDORI', 'ANGEL ADOLFO QUISPE ROJAS', 'ANGEL QUISPE MERINO', 'ANGEL REYNOSO', 'ANGEL EDUARDO REYNOSO QUISPE', 'ALINK PLU DB', 'ALEX COOL MID', 'ALVAREZ ZAMORA STIVEN', 'ALVARO DILAN ROJAS', 'ANDERSON SANCHEZ', ' ANGELA ANGUIE (ALDAIR HC)'
        , 'ANDERSON ERIK SANCHEZ SOLANO', 'ANGEL GABRIEL GAMARRA QP', 'ALDAIR HC', 'ALDAHIR JORDAN ÑIQUE ROJAS', 'ANTHONY S-M', 'ABEL BL', 'ALEXANDER MUÑOZ ARTEAGA', 'ARMANDO LOPEZ', 'ANDRES LOPEZ', 'ANDRES MACAVILCA COLQUE', 'BATRA CRISTIAN', 'BLADIMIR ANGEL MAMANI YANA'
        , 'BRYAN AQ', 'BRAYHAN DANS MAVERICK', 'BRAYAN ANGEL BRAVO SOTO', 'BENITO ANTONY QUISPE ATAHUALPA', 'CHRIS QUILL', 'CRISTIAN JONATHAN CAMPOS CARHUALLANQUI', 'CARLOS ALFONSO REQUEJO PALOMINO', 'CARLOS ALFREDO RONDA VALDIVIEZO', 'CARLOS BLACKER LAZARO MACHACA', 'CARLOS CÑ'
        , 'CARLOS ALBERTO SOSA PEÑALOZA', 'CARLOS ALBERTO COZ QUITÓ', 'CAROL VILCAPOMA JIMÉNEZ', 'CLEVER ANTHONY CRUZ', 'CRISTHIAN PAUL SOLIS PEREZ', 'CRISTIAN CHUQUIZUTA', 'CAMUZ SANCHEZ', 'DANY DE CONTRERAS', 'DAMIAN JESUS MACIAS', 'DIXON OVALLE', 'DAVID ORTIZ', 'DAVID AMORIN', 'DAVID CONDORI HUAMANHUILCA',
        'DER KEGEL (ALDAIR HC)', 'Darem Brando Rupa Carmona', 'DIEGO JOSE MARALLANO PEREZ', 'ERICK ERQUIÑIGO RIOS', 'ERICK QH', 'ELTIO RIAL', 'ERICK STOREE', 'ERICK BRANDON TONCONI CHAMBILLA', 'ELVIS VARGAS AREVALOELVIS VARGAS AREVALO', 'ELMER PERCY PORRAS HUAMANI', 'ESTEBAN SANCHEZ'
        , 'ENRIQUE GUTIERREZ VARGAS', 'EDGAR LUIS MEJIA SALINAS', 'ENRIQUE PALACIOS', 'EDWIN CRISTOBAL REYES MEZA', 'FERNANDEZ FERNANDEZ JUAN CARLOS (MAFIA AREQUIPEÑA)', 'FLORES MENESES MAYCOL FRANKLIN', 'FRANK SUAREZFRANK SUAREZ', 'FRANK EDUARDO PEÑA CHIPANA', 'FRANSISCO VALDERRAMA', 'FRANK VILCA RAMIREZ'
        , 'FRANK FARID JARA CALZADA', 'FREDDY MARTIN SABRERA YLLA', 'FRET JONATAN JAMANCA CRISOLO', 'FRANCO GOMEZ', 'FRANK ABEL IMA RUIZ', 'FILIPPO BLAS', 'FELIPE FREDDY', 'GABRIEL ROJAS PRADO', 'GIANCARLO MENDOZAC', 'GEAN QUILLATUPA', 'GEYSON ATENCIO LLANTOY', 'GOES D JESUS', 'GERAL CESAR TORRES RAMOS'
        , 'HARRY LAZO BRAVO', 'HENRY GILES TELLO', 'IVAN CASAS SANDOVAL (DIAMANTES FREE FIRE)', 'JAMES COAQUIRA', 'JAVIER CRISTHIAN FIGUEROA ARCE', 'JAIR ANTHONY PORRAS', 'JAIR ANTHONY PORRAS QUISPE', 'JESUS MONAR ROMAN', ' JONATAN GL', 'JHORDY JAMIR CABRERA NONTOL', ' JOB ANTONI MANGUIA PALACIOS'
        , 'JULIO RÍOS MURILLO', 'JULIO RIVERS', 'Jorge Augusto Pando Segura', 'JOSE MAGUIÑA', ' JOSE ANTONIO MAGUIÑA RAMIREZ', 'JOSHUA MOSS', 'JOSHUA BOSTING', 'JOSHUA MOSSTV', 'JOSSEMAR MEDRANO SORAS', 'JASER MEDRANO', 'JHANS FLORES TOVAR', 'Jimmy Tiziu Usnayo Peña', 'JHON ABEL HUALLPA QUISPE', 'JHON HQ'
        , 'JORGE LUIS HUANCA MAMANI', ' JORGE MANUEL HERRERA MALDONADO', 'JORGE EDUARDO GONZALES NIETO', 'JEFERSON LANDA SALCEDO', 'JUNIOR JOEL LEON VARGAS', 'JOSE MARTIN VALDIVIA LLANOS', 'JOSE CHRISTIAN COLQUE CASTRO', 'JOSE ELIAS LLERENA GUTIERREZ', 'JOSEPH LUIS GARIBAY REYES', 'JUAN BRAYAN ESPINOZA NUÑEZ'
        , 'JOSEPH GARIBAY', 'JOHN T LH', 'JASON SMITH', 'JESUS CACERES', 'JOEL ENRIQUEZ FERNANDEZ', 'JOSSEMAR MEDRANO SORAS', 'JOSE FERNANDO INGA BELITO', 'JAMYL LUIS', 'JHONATHAN RIVEROS', 'JUAN JOSE VASQUEZ MOLINA', 'JUAN EMILIO HURTADO CILCCHE', 'JUAN FERNANDO ZUÑIGA LOPEZ', 'JUAN CESAR FLORES'
        , 'JUAN FERNANDEZ', 'JUAN CARLOS CAMACHO', 'JUAN CARLOS MOSQUIPA ACUÑA', ' JUNIOR CC (TROVO)', 'JOSE JOSE P-C', 'JOSUE STEVEN BERNABE CASTRO', 'JORGE AUGUSTO PANDO SEGURA', 'JHOVER RAMIREZ FUENTES', 'JAMYL BRANDOM LUIS GOMEZ', 'KEVIN CESAR VILCAPOMA JIMÉNEZ', 'KEV ZLATAN VJ', 'KEVIN MARCO CARREÑO ROMERO'
        , 'LUIS ALBERTO ORE TAPIA', 'LUIS ALBERTO ORE TAPIA', 'LUIS GOMEZ JAMYL BRANDON', 'LUDEYVY RUIZ SILVA', 'LUCIO ROPERTO QUISPE CUTIPA', 'LOSS MRR', 'LONES REYDAVID', ' LORENZO MASNA (USA YAPE A NOMBRE DE VANESSA KARINA CONDORI MOREANO', 'LUIS ALEJANDRO GUTIERREZ MOLINA', 'LUIS MARCK', 'LUIS MARCK ANTHONY'
        , 'LUIS MARCK ANT OREJON BACILIO', 'LUNA NAOMI', 'MARTIN URQUIZA SANCHEZ', 'MARTIN PAUL CHAVEZ TAIRO', 'MANUEL JUNIOR CHIRINOS APARICIO', 'MOISES IVAN GUTIERREZ ALARCON', 'MARCOS CRUZADO PEREZ', 'MARCOS B!BARBOZA', 'MASSIMO ESPINOZA', 'MANSILLA DANIEL', 'MICAELA ALVARADO', 'MANUEL HUILLCA'
        , 'MARY ESTEFANY VILCA SOTO( YAPE DE BENITO ANTONY)', 'MIGUEL ÁNGEL LQ', 'MARCK BO', ' MARCK OB', 'MIGUEL LA MELODIA DE LA CALLE MIGUEL ANGEL', 'MACAVILCA COLQUE ANDRES', 'NUÑEZ BRYN', 'OMAR FERREYRA (SUPLANTADO NO VENDE NADA)', 'PIERO ANDRE GOMEZ GONZALEZ', 'PATRICK ALEXIS NAVARRO SILVERA', 'P-C JOSE JOSE'
        , 'ROBERTO ALFRE ALDAVE GARCILAZO', 'RUSBEL SEDANO TAIPE', 'RONALD JHONNEL RUIZ SILVA', 'RICK DREE', 'ROYER VALDI', 'ROGER ANDRES VALVIVIEZO', 'ROGER ANDRES HUARCAYA VALVIVIEZO', 'RAIDEN LAO', 'ROBINSON NICK QUISPE PARI', 'ROLANDO RODRIGO CASTILLO CAMPOS', 'ROUSSE KIARA GAMARRA FALCON', 'RODRIGO JOEL SOTO MAMANI'
        , 'RICHARD JHERSON QI', 'RENZO ESTEFANO ROCHABRUN DIAZ', 'RENZO MOISES AGUILAR MARIN', 'STIVEN ALVAREZ ZAMORA', 'SHERLEY MARIA HUERTA PRECIADO', 'SHESSIRA GERALDINE TORRES RAMOS', 'SABINA CRISTINA NAHUE MENDOZA (FREE FIRE)', 'TOMAS WILFRIDO GONZALES ROJAS', 'VICTOR JULIO RIOS MURILLO', 'VICTOR IMA RUIZ'
        , 'VORG SANGER', 'YHONI GONZO', 'YEFRI ANDERSON', 'YEISON B!BARBOZA', 'YESLIN MUÑOZ', 'YEISON SEGUNDO SOTO CUBAS', 'YHERALDIN TORRES FER', 'YAN GARCIA', 'YOLANDA APONTE DE VENEGAS', 'THIAGO MEZA CRUZADO', 'TAYTAN CHUCHO', 'WALTER OLGER VER'];
    searchInput.addEventListener('input', function () {
        const searchTerm = searchInput.value.toLowerCase();
        const filteredEstafadores = estafadores.filter(function (estafador) {
            return estafador.toLowerCase().includes(searchTerm);
        });

        displayEstafadores(filteredEstafadores, searchTerm); // Pasar searchTerm como argumento
    });

    function displayEstafadores(estafadores, searchTerm) {
        ul.innerHTML = ''; // Limpiar la lista ul
        estafadores.forEach(function (estafador) {
            const li = document.createElement('li');
            li.textContent = estafador;
            ul.appendChild(li);
        });

        if (searchTerm && estafadores.length > 0) {
            estafadoresList.style.display = 'block'; // Mostrar la lista si searchTerm no está vacío y hay resultados
        } else {
            estafadoresList.style.display = 'block'; // Ocultar la lista si searchTerm está vacío o no hay resultados
        }
    }

    // Mostrar todos los estafadores al cargar la página
    displayEstafadores(estafadores, ''); // Pasar una cadena vacía como searchTerm inicialmente
});